apiVersion: v1
kind: PersistentVolume
metadata:
  name: kodofs-csi-pv
  labels:
    kodofs-pvname: kodofs-csi-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: kodofsplugin.storage.qiniu.com
    volumeHandle: kodofs-csi-pv
    nodePublishSecretRef:
      name: kodofs-csi-pv-secret
      namespace: default
