apiVersion: v1
metadata:
  name: kodofs-csi-pv-secret
kind: Secret
type: Opaque
data:
  gatewayid: "MUST FILL OUT THIS FIELD"
  mntsvraddr: "MUST FILL OUT THIS FIELD"
  accesstoken: "MUST FILL OUT THIS FIELD"
