apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kodo-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ''
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      kodo-pvname: kodo-csi-pv
