apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kodo
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.0-alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: kodo-pvc
            mountPath: "/data"
      volumes:
        - name: kodo-pvc
          persistentVolumeClaim:
            claimName: kodo-pvc
