apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kodofs-csi-sc
parameters:
  fstype: "0"
  blocksize: "4194304"
  csi.storage.k8s.io/provisioner-secret-name: kodofs-csi-sc-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
provisioner: kodofsplugin.storage.qiniu.com
reclaimPolicy: Retain
