# github action 构建一个docker项目
name: Build Docker Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Apt install
        run: sudo apt-get install -y git make

      - name: Build docker image
        run: make build_image

  build-executable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Apt install
        run: sudo apt-get install -y git make

      - uses: actions/setup-go@v4
        with:
          go-version: "^1.18"

      - name: Build executable
        run: make build
