on:
  push:
    tags:
      - "v*"
name: Build Release
jobs:
  create_release:
    name: Create release for new version
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release Notes
          draft: true
          prerelease: false

  upload_yaml:
    name: Release kodo/kodofs plugin yaml files
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: build
        run: make k8s/kodo.yaml && make k8s/kodofs.yaml

      - name: Upload kodo.yaml files to Release Asset
        id: upload-release-asset-kodo.yaml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./k8s/kodo.yaml
          asset_name: kodo-plugin.yaml
          asset_content_type: plain/text

      - name: Upload kodofs.yaml files to Release Asset
        id: upload-release-asset-kodofs.yaml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./k8s/kodofs.yaml
          asset_name: kodofs-plugin.yaml
          asset_content_type: plain/text
